 Time to read keyword file =  1.188 seconds
Warning -Duplicate keyword: CONTROL_MPP_CONTACT_GROUPABLE 
  Warning occurs in file C:\Users\adity\Desktop\COMMAS\Sem 3\CHBM\Project\Files\ViVA_FrontalImpact_SimplifiedNeck\FrontalImpact_modified\run_frontal_impact.key
Data input seq. 12 from file VIVA_OpenHBM_F50_HN_Contacts_SCspine_20160912.key
Data input seq. 14 from file run_frontal_impact.key
Last one will be used
Message 0
 Time to read keyword file =  0.375 seconds
Message 0
